[package]
name = "render"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
pollster = "0.4.0"
wasm-bindgen = "0.2.100"
wgpu = { version = "25.0.0", default-features = false, features = ["webgpu", "wgsl"] }
